import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Container.module.css'
import React, { useState } from "react";
import dynamic from "next/dynamic";
import Header from './components/Header/Header';

//server imports
import { CacheManager } from '../helpers/CacheManager';

const Home: NextPage = (props:any) => {
  const Map = dynamic(
    () => import("./components/SkillTree/SkillTree"), 
    { ssr: false }
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{props.test}</h1>
      <Header />
      <Map />
    </div>
  )
}

// export const getServerSideProps = async () => {

  
// }


export default Home
