import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Container.module.css'
import React, { useState } from "react";
import dynamic from "next/dynamic";
import Header from './components/Header/Header';

//server imports
import { CacheManager } from '../helpers/CacheManager';

const Home: NextPage = (props:any) => {
  const Map = dynamic(
    () => import("./components/SkillTree/SkillTree"), 
    { ssr: false }
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{props.test}</h1>
      <Header />
      <Map />
    </div>
  )
}

export const getServerSideProps = async () => {
  // if(CacheManager.has("userData")){
  //   return {props:{test:CacheManager.get("userData")[0].email}}
  //   return {props:{test:CacheManager.get("userData")}}
  // }else{
  //   return fetch("http://localhost:4000/api/users")
  //   .then(res => res.json()).then(res => {
  //     CacheManager.set("userData", res);
  //     return {props:{test:"something"}}
  //   })
  //   .catch(()=>{
  //     return {props:{test:"nothing"}}
  //   })
    
  // }
  
}


export default Home
